apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
  namespace: roboshop
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: {{ .Values.secrets.rabbitmq.user | quote }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.secrets.rabbitmq.password | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: {{ .Values.images.rabbitmq }}
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
spec:
  selector:
    app: rabbitmq
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672
