---
- name: Install Roboshop via local Helm chart
  kubernetes.core.helm:
    name: roboshop
    chart_ref: "{{ role_path }}/files/helm/roboshop"
    release_namespace: "{{ roboshop_namespace }}"
    create_namespace: true
    wait: true
    timeout: "10m"
    values:
      images: "{{ roboshop_images }}"
      secrets:
        mysql:
          rootPassword: "{{ mysql_root_password }}"
          password:     "{{ mysql_password }}"
        rabbitmq:
          user:     "{{ rabbitmq_user }}"
          password: "{{ rabbitmq_password }}"
        payment:
          amqpUser: "{{ payment_amqp_user }}"
          amqpPass: "{{ payment_amqp_pass }}"
